.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1400intrNan512
DRV_DEF = 1400_intr_drv.def
DRV_LIST = 1400_intr_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
