.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = strs377_id32050103_nano_v3
DRV_DEF = strs377_nano_v3.def
DRV_LIST = strs377_id32050103_nano_v3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

