.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 700NanPrf_v1
DRV_DEF = Prof_700_nano.def
DRV_LIST = Prof_700_nano.obj

include $(BuildKrotXML)\drivers\nano\nano_v1\nano_v1_core.mk 

