.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1200StrsBpsNan512
DRV_DEF = strs_1200_bps_drv.def
DRV_LIST = strs_1200_bps_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

