.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1000Cor_introscop
DRV_DEF = coros_1000_introskop.def
DRV_LIST = coros_1000_introskop.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

