.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = Cor_426_nv3
DRV_DEF = Cor_426_nv3.def
DRV_LIST = Cor_426_nv3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

