.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 700StrsNan512
DRV_DEF = strs_700_drv.def
DRV_LIST = strs_700_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
