.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 5300CorNan512
DRV_DEF = coros_5300_drv.def
DRV_LIST = coros_5300_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

