.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1216intrNan512
DRV_DEF = 1216_intr_drv.def
DRV_LIST = 1216_intr_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
