.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 100NanPrf_v3
DRV_DEF = Prof_100_nano.def
DRV_LIST = Prof_100_nano.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

