.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = Prof_1400_nano_v3
DRV_DEF = Prof_1400_nano_v3.def
DRV_LIST = Prof_1400_nano_v3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

