.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 800StrsNan512
DRV_DEF = strs_800_drv.def
DRV_LIST = strs_800_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
