.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = strs500_id53100104_nano_v3
DRV_DEF = strs500_id53100104_nano_v3.def
DRV_LIST = strs500_id53100104_nano_v3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

