.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 426CorNan512
DRV_DEF = coros_426_drv.def
DRV_LIST = coros_426_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
