.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 30inch_TFI_drv
DRV_DEF = 30inch_TFI_drv.def
DRV_LIST = 30inch_TFI_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

