.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = raw_data_drv
DRV_DEF = raw_data_drv.def
DRV_LIST = raw_data_drv.obj

include $(BuildKrotXML)\drivers\experimental.drv\raw_data\raw_data_core.mk

