.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1200CorBpsNan512
DRV_DEF = coros_1200_bps_drv.def
DRV_LIST = coros_1200_bps_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

