.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = coros_700_introskop
DRV_DEF = coros_700_introskop.def
DRV_LIST = coros_700_introskop.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

