.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1400StrsNan512
DRV_DEF = strs_1400_drv.def
DRV_LIST = strs_1400_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
