.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 4200CorNan512
DRV_DEF = coros_4200_drv.def
DRV_LIST = coros_4200_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
