.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1200NanPrf_v1_1000bochka
DRV_DEF = Prof_1000_nano.def
DRV_LIST = Prof_1000_nano.obj

include $(BuildKrotXML)\drivers\nano\nano_v1\nano_v1_core.mk 

