.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1200intrNan512
DRV_DEF = 1200_intr_drv.def
DRV_LIST = 1200_intr_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
