.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = coros_700_dop_poyas
DRV_DEF = coros_700_dop_poyas.def
DRV_LIST = coros_700_dop_poyas.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

