.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1400corNan512
DRV_DEF = cor_1400_drv.def
DRV_LIST = cor_1400_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
