.PHONY: all clean

include $(BuildKrotW32)\defaults.mk

TARGET = krotw32.res

SRC = \
anomal.bmp \
bad_styk.bmp \
bobish.bmp \
category.bmp \
CHKBOFF.BMP \
CHKBON.BMP \
crack.bmp \
cracks.bmp \
crzgroup.bmp \
defekt.bmp \
endprgrz.bmp \
endsprl.bmp \
getplace.bmp \
kanavHor.bmp \
kanavVer.bmp \
kran.bmp \
looping_in.bmp \
looping_out.bmp \
magnit.bmp \
marker.bmp \
marktime.bmp \
mehan.bmp \
musor.bmp \
otvod.bmp \
oval.bmp \
patron.bmp \
patron_in.bmp \
patron_out.bmp \
plastina.bmp \
povorot.bmp \
prigruz.bmp \
prileganie.bmp \
privarka.bmp \
runplace.bmp \
shov_b.bmp \
shov_p.bmp \
shov_s.bmp \
shov_n.bmp \
speedBck.bmp \
speedDn.bmp \
speedFwd.bmp \
speedStop.bmp \
speedUp.bmp \
startprgrz.bmp \
startspr.bmp \
stress.bmp \
tehokno.bmp \
thick.bmp \
thickdn.bmp \
thickup.bmp \
troynik.bmp \
vmyat.bmp \
vog.bmp \
waterin.bmp \
waterout.bmp \
zaplat.bmp \
zaplat1.bmp \
zavarka.bmp \
prokat.bmp \
mufta_in.bmp \
mufta_out.bmp \
gofra.bmp \
\
ID_022.bmp \
ID_025.bmp \
ID_027.bmp \
ID_029.bmp \
ID_031.bmp \
ID_032.bmp \
ID_033.bmp \
ID_034.bmp \
ID_164.bmp \
ID_165.bmp \
ID_166.bmp \
ID_167.bmp \
ID_194.bmp \
ID_195.bmp \
ID_200.bmp \
ID_201.bmp \
ID_202.bmp \
ID_203.bmp \
ID_204.bmp \
ID_205.bmp \
ID_206.bmp \
ID_207.bmp \
ID_208.bmp \
ID_210.bmp \
ID_211.bmp \
ID_212.bmp \
ID_213.bmp \
ID_214.bmp \
ID_215.bmp \
ID_216.bmp \
ID_218.bmp \
ID_219.bmp \
ID_220.bmp \
ID_221.bmp \
ID_222.bmp \
ID_223.bmp \
ID_224.bmp \
ID_225.bmp \
ID_226.bmp \
ID_227.bmp \
ID_228.bmp \
ID_229.bmp \
ID_230.bmp \
ID_231.bmp \
ID_232.bmp \
ID_233.bmp \
ID_234.bmp \
ID_236.bmp \
\
CLOCK01.ICO \
DAIRUN.ICO \
DAISTOP.ICO \
EYE.ICO \
gpas01.ico \
graph2.ICO \
company.ico \
krot01.ico \
MAIL14.ICO \
MONITR01.ICO \
objEdit.ICO \
objFltr.ICO \
recView.ICO \
Settings.ICO \
tubeFltr.ICO \
\
logo.bmp \
\
blackvog.cur \
empty.CUR \
H_NW.CUR \
WHITEVOG.CUR \
\
expstr.h \
\
expstr.rc \
krotw32.rc

all: $(TARGET)

$(TARGET): $(SRC)
	$(PRG_RC) krotw32.rc

clean:
	-$(DEL) $(TARGET) >nul
