.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 4215_intr_nan512
DRV_DEF = intr_4215_drv.def
DRV_LIST = intr_4215_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

