.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 700CorNan512_72000102
DRV_DEF = coros_700_drv.def
DRV_LIST = coros_700_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

