.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 30inchCorNan512
DRV_DEF = coros_30inch_drv.def
DRV_LIST = coros_30inch_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

