.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 500StrsNan512
DRV_DEF = strs_500_drv.def
DRV_LIST = strs_500_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
