.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = Prof_1022_enc
DRV_DEF = Prof_1022_enc.def
DRV_LIST = Prof_1022_enc.obj

include $(BuildKrotXML)\drivers\nano\nano_v1\nano_v1_core.mk 

