.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 460CorNan512
DRV_DEF = coros_460_drv.def
DRV_LIST = coros_460_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

