.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = intr325_id3201010444
DRV_DEF = intr325_id3201010444.def
DRV_LIST = intr325_id3201010444.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

