.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = proba_test.dll
DRV_DEF = proba_test.def
DRV_LIST = proba_test.obj

include $(BuildKrotXML)\drivers\nano\nano_lc\nano_lc_core.mk 

