DB_LOG _trcobj.log

DB_MAKE _trcobj.mdb trcobj.def

INSERT INTO dct_feat_size (id, name, code_name) VALUES (0, 'NULL', 'NONE')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (1, 'Продольная канавка', 'AXGR')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (2, 'Продольная щель', 'AXSL')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (3, 'Поперечная канавка', 'CIGR')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (4, 'Поперечная щель', 'CISL')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (5, 'Обширный', 'GENE')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (6, 'Язва', 'PINH')
INSERT INTO dct_feat_size (id, name, code_name) VALUES (7, 'Каверна', 'PITT')

INSERT INTO objtypes (id, name, tbl)      VALUES (4,   'Гофра', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (5,   'Аномалия', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (6,   'Продольная трещина', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (7,   'Зона коррозии', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (8,   'Канавка продольная', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (9,   'Канавка поперечная', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (10,  'Каверна', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (11,  'Приварка', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (12,  'Мехповреждение', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (13,  'Стресс-коррозия', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (14,  'Зона трещин', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (15,  'Вмятина', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (16,  'Овальность', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (17,  'Дефектный стык', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (18,  'Заварка', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (19,  'Прилегание мет. предмета', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (20,  'Тех.окно', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (21,  'Изоляционный стык', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (22,  'Патрон малой длины', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (23,  'Хомут', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (24,  'Задвижка', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (25,  'Маркерное кольцо', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (26,  'Маркер магнитный', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (27,  'Заварка бобышки', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (28,  'Рем. накладка, зашлиф. и т.п.', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (29,  'Отрем. участок', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (30,  'Камера запуска', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (31,  'Нераспозн. объект', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (32,  'Трубн. арматура', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (33,  'Элемент обустройства', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (34,  'Недопуст. конструкт. эл-т', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (40,  'Камера приема', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (60,  'Конец участка пригрузов', '')
INSERT INTO objtypes (id, name, tbl)      VALUES (70,  'Кран', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (80,  'Маркер', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (81,  'Таймерный маркер', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (110, 'Начало участка пригрузов', '')
INSERT INTO objtypes (id, name, tbl)      VALUES (120, 'Прямая врезка', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (130, 'Вход в патрон', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (131, 'Выход из патрона', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (132, 'Тройник', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (133, 'Вход в лупинг', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (134, 'Выход из лупинга', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (140, 'Переход толщины', 'thick')
INSERT INTO objtypes (id, name, tbl)      VALUES (141, 'Категория участка', 'thick')
INSERT INTO objtypes (id, name, tbl)      VALUES (160, 'Поворот', 'turn')
INSERT INTO objtypes (id, name, tbl)      VALUES (161, 'Вход в воду', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (162, 'Выход из воды', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (163, 'Дефект проката', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (164, 'Начало рем. муфты', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (165, 'Конец рем. муфты', 'lin_obj')
INSERT INTO objtypes (id, name, tbl)      VALUES (170, 'Пригруз', '')
INSERT INTO objtypes (id, name, tbl, off) VALUES (180, 'Расхождение между прогонами', '', 1)
INSERT INTO objtypes (id, name, tbl)      VALUES (190, 'Прямошовная труба', 'weld')
INSERT INTO objtypes (id, name, tbl)      VALUES (191, 'Спиралешовная труба', 'weld')
INSERT INTO objtypes (id, name, tbl)      VALUES (192, 'Беcшовная труба', 'weld')
INSERT INTO objtypes (id, name, tbl)      VALUES (193, 'Неопределенная секция', 'weld')
INSERT INTO objtypes (id, name, tbl)      VALUES (194, 'Одношовная', 'weld')
INSERT INTO objtypes (id, name, tbl)      VALUES (195, 'Двухшовная', 'weld')
INSERT INTO objtypes (id, name, tbl)      VALUES (200, 'Аном. облицовки шва', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (201, 'Корр. на кольцев. шве', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (202, 'Непровар / утяжина', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (203, 'Подрез', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (204, 'Смещение кромок', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (205, 'Правка кромок', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (206, 'Подкладное кольцо', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (207, 'Аном. продольн. шва', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (208, 'Аном. спиральн. шва', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (209, 'Вмят. с деф. потери мет.', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (210, 'Внутристенное расслоение', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (211, 'Наруш. адгезии изоляц. трубы кон.', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (212, 'Наруш. адгезии изоляц. трубы нач.', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (213, 'Несваренный стык патрона', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (214, 'Эксцентричный патрон', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (215, 'Потеря конт. с трубой', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (216, 'Зашлифовка', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (217, 'Потеря металла', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (218, 'Точечная коррозия', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (219, 'Поджиг', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (220, 'Расслоение с вых. на пов-ность', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (221, 'Заварка отверстия', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (222, 'Трещина на кольцевом шве', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (223, 'Несплошность плоскостного типа', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (224, 'Поперечная трещина', 'defect')
INSERT INTO objtypes (id, name, tbl)      VALUES (225, 'Зашлифовка продольного шва', 'defect')

INSERT INTO trcConfig (distMode, odoKoef, odoStart) VALUES (0, 1, 0)
