.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 426NanPrf_v1
DRV_DEF = Prof_426_nano.def
DRV_LIST = Prof_426_nano.obj

include $(BuildKrotXML)\drivers\nano\nano_v1\nano_v1_core.mk 

