.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 20inchCorNan512
DRV_DEF = coros_20inch_drv.def
DRV_LIST = coros_20inch_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

