.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = profil_7220_lc.dll
DRV_DEF = profil_7220_lc.def
DRV_LIST = profil_7220_lc.obj

include $(BuildKrotXML)\drivers\nano\nano_lc\nano_lc_core.mk 

