.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 700StrsNan512_7211
DRV_DEF = strs_700_drv_7211.def
DRV_LIST = strs_700_drv_7211.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
