.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = Strs_600_nano_v3
DRV_DEF = Strs_600_nano_v3.def
DRV_LIST = Strs_600_nano_v3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

