.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1406corNan512
DRV_DEF = cor_1406_drv.def
DRV_LIST = cor_1406_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
