.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = coros_700_8201_MFL_plus
DRV_DEF = coros_700_8201_MFL_plus.def
DRV_LIST = coros_700_8201_MFL_plus.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

