.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = coros_800_7201
DRV_DEF = coros_800_7201.def
DRV_LIST = coros_800_7201.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

