.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = Cor_200_nano_v3
DRV_DEF = Cor_200_nano_v3.def
DRV_LIST = Cor_200_nano_v3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

