.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

all:
	$(MAKE) -C _16inch_coros
	$(MAKE) -C _16inch_prof
	$(MAKE) -C _16inch_strs
	$(MAKE) -C _20inch_profil
	$(MAKE) -C _30inch_prof
	$(MAKE) -C _8inch_coros
	$(MAKE) -C 100_coros
	$(MAKE) -C 100_profil
	$(MAKE) -C 1400_profil
	$(MAKE) -C 1400_profil_ID1422
	$(MAKE) -C 200_coros 
	$(MAKE) -C 200_profil
	$(MAKE) -C 200_strs
	$(MAKE) -C 273_profil
	$(MAKE) -C 273_stress
	$(MAKE) -C 325_coros
	$(MAKE) -C 325_coros_id32050103
	$(MAKE) -C 325_coros_id321501
	$(MAKE) -C 325_introskop_id3201010444
	$(MAKE) -C 325_prof_id3222
	$(MAKE) -C 325_profil
	$(MAKE) -C 325_stress
	$(MAKE) -C 325_strs_id32050103
	$(MAKE) -C 377_cor
	$(MAKE) -C 377_strs_id32050103
	$(MAKE) -C 377_strs_id37100103
	$(MAKE) -C 426_coros
	$(MAKE) -C 426_stress
	$(MAKE) -C 426_strs_id32050103
	$(MAKE) -C 500_strs_id53100104
	$(MAKE) -C 508_stres
	$(MAKE) -C 600_coros
	$(MAKE) -C 600_profil
	$(MAKE) -C 600_stres
	$(MAKE) -C 660_coros 
	$(MAKE) -C 660_profil

clean:
	$(MAKE) -C _16inch_coros clean
	$(MAKE) -C _16inch_prof clean
	$(MAKE) -C _16inch_strs clean
	$(MAKE) -C _20inch_profil clean
	$(MAKE) -C _30inch_prof clean
	$(MAKE) -C _8inch_coros clean
	$(MAKE) -C 100_coros  clean
	$(MAKE) -C 100_profil clean
	$(MAKE) -C 1400_profil  clean
	$(MAKE) -C 1400_profil_ID1422 clean
	$(MAKE) -C 200_coros  clean  
	$(MAKE) -C 200_profil clean  
	$(MAKE) -C 200_strs clean
	$(MAKE) -C 273_profil clean
	$(MAKE) -C 273_stress clean
	$(MAKE) -C 325_coros  clean
	$(MAKE) -C 325_coros_id32050103 clean
	$(MAKE) -C 325_coros_id321501 clean
	$(MAKE) -C 325_introskop_id3201010444 clean
	$(MAKE) -C 325_prof_id3222 clean
	$(MAKE) -C 325_profil clean  
	$(MAKE) -C 325_stress clean  
	$(MAKE) -C 325_strs_id32050103 clean
	$(MAKE) -C 377_cor clean
	$(MAKE) -C 377_strs_id32050103 clean
	$(MAKE) -C 377_strs_id37100103 clean
	$(MAKE) -C 426_coros clean
	$(MAKE) -C 426_stress clean
	$(MAKE) -C 426_strs_id32050103 clean
	$(MAKE) -C 500_strs_id53100104 clean
	$(MAKE) -C 508_stres  clean
	$(MAKE) -C 600_coros  clean
	$(MAKE) -C 600_profil clean
	$(MAKE) -C 600_stres  clean
	$(MAKE) -C 660_coros  clean
	$(MAKE) -C 660_profil clean  

