.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1000CorNan512
DRV_DEF = coros_1000_drv.def
DRV_LIST = coros_1000_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

