.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1000StrsNan512
DRV_DEF = strs_1000_drv.def
DRV_LIST = strs_1000_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

