.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = Prof_id1422_nv3
DRV_DEF = Prof_id1422_nv3.def
DRV_LIST = Prof_id1422_nv3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

