all: VogCorrj.dll

COMPILE_FLAGS = /cc /U"\\Nikonov\D\Borland\Delphi 3\lib"
INCLUDE_FILES = krotapi.pas 
VogCorrj.dll: vogcorrj.dpr $(INCLUDE_FILES)
 "\\Nikonov\d\borland\delphi 3\bin\dcc32" $(COMPILE_FLAGS) vogcorrj.dpr

