.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1416intrNan512
DRV_DEF = intr_1416_drv.def
DRV_LIST = intr_1416_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
