.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 500NanPrf_5320
DRV_DEF = Prof_5320_nano.def
DRV_LIST = Prof_5320_nano.obj

include $(BuildKrotXML)\drivers\nano\nano_v1\nano_v1_core.mk 

