.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 5311StrsNan512
DRV_DEF = strs_5311_drv.def
DRV_LIST = strs_5311_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 
