.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 1213StrsBpsNan512
DRV_DEF = strs_1213_bps_drv.def
DRV_LIST = strs_1213_bps_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

