.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

all:
	$(MAKE) -C nano_512
	$(MAKE) -C nano_v3
	$(MAKE) -C nano_v1

clean:
	$(MAKE) -C nano_512 clean
	$(MAKE) -C nano_v3 clean
	$(MAKE) -C nano_v1 clean
