.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 325NanPrf_v1
DRV_DEF = Prof_325_nano.def
DRV_LIST = Prof_325_nano.obj

include $(BuildKrotXML)\core\drivers\nano\nano_v1\nano_v1_core.mk 

