.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 500CorNan512
DRV_DEF = coros_500_drv.def
DRV_LIST = coros_500_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

