.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

all:
	$(MAKE) -C _20inch508_coros
	$(MAKE) -C _30inch762_coros
	$(MAKE) -C 1000_coros
	$(MAKE) -C 1000_stres
	$(MAKE) -C 1200_coros
	$(MAKE) -C 1200_coros_bps
	$(MAKE) -C 1200_stres
	$(MAKE) -C 1200_stres_bps
	$(MAKE) -C 426_coros
	$(MAKE) -C 1400_stres
	$(MAKE) -C 1400_coros
	$(MAKE) -C 460_coros
	$(MAKE) -C 500_coros_504sens
	$(MAKE) -C 500_stres
	$(MAKE) -C 700_stres
	$(MAKE) -C 700_stress_7211
	$(MAKE) -C 800_stres
	$(MAKE) -C 426_coros_id4200
	$(MAKE) -C 500_coros_660sens_id5301
	$(MAKE) -C 700_coros_72000102
	$(MAKE) -C 700_coros_7201_dop_poyas
	$(MAKE) -C 700_coros_7201_introskop
	$(MAKE) -C 500_stres_id5311
	$(MAKE) -C 1000_coros_introskop_10060102
	$(MAKE) -C 800_coros_7201
	$(MAKE) -C 700_cor_8201_MFL_plus
	$(MAKE) -C 500_intr_id5300
	$(MAKE) -C _30inch_TFI
	$(MAKE) -C 1400_introskop
	$(MAKE) -C 1200_introskop_id1215

clean:
	$(MAKE) -C _20inch508_coros clean
	$(MAKE) -C _30inch762_coros clean
	$(MAKE) -C 1000_coros clean
	$(MAKE) -C 1000_stres clean
	$(MAKE) -C 1200_coros clean
	$(MAKE) -C 1200_coros_bps clean
	$(MAKE) -C 1200_stres clean
	$(MAKE) -C 1200_stres_bps clean
	$(MAKE) -C 426_coros  clean
	$(MAKE) -C 1400_stres clean
	$(MAKE) -C 1400_coros clean
	$(MAKE) -C 460_coros  clean
	$(MAKE) -C 500_coros_504sens clean
	$(MAKE) -C 500_stres  clean
	$(MAKE) -C 700_stres  clean
	$(MAKE) -C 700_stress_7211 clean
	$(MAKE) -C 800_stres  clean
	$(MAKE) -C 426_coros_id4200 clean
	$(MAKE) -C 500_coros_660sens_id5301 clean
	$(MAKE) -C 700_coros_72000102 clean
	$(MAKE) -C 700_coros_7201_dop_poyas clean
	$(MAKE) -C 700_coros_7201_introskop clean
	$(MAKE) -C 500_stres_id5311 clean
	$(MAKE) -C 1000_coros_introskop_10060102 clean
	$(MAKE) -C 800_coros_7201 clean
	$(MAKE) -C 700_cor_8201_MFL_plus clean
	$(MAKE) -C 500_intr_id5300 clean
	$(MAKE) -C _30inch_TFI clean
	$(MAKE) -C 1400_introskop clean
	$(MAKE) -C 1200_introskop_id1215 clean

