.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = 20inchNanPrf_v3
DRV_DEF = Prof_20inch_nano.def
DRV_LIST = Prof_20inch_nano.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

