.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = samopis_nano_V1
DRV_DEF = samopis_nano_V1.def
DRV_LIST = samopis_nano_V1.obj

include $(BuildKrotXML)\drivers\nano\nano_v1\nano_v1_core.mk 

