.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = cor325_id32050103_nano_v3
DRV_DEF = cor325_nano_v3.def
DRV_LIST = cor325_id32050103_nano_v3.obj

include $(BuildKrotXML)\drivers\nano\nano_v3\nano_v3_core.mk 

