.PHONY: all clean

include $(BuildKrotXML)\defaults.mk

TARGET = raw_30_md33
DRV_DEF = raw_30_md33_drv.def
DRV_LIST = raw_30_md33_drv.obj

include $(BuildKrotXML)\drivers\nano\nano_512\nano_512_core.mk 

